cards:
  "3082": "Основная карта"
  "2415": "Дополнительная карта"
  "9624": "Карта для переводов"
  "6274": "Карта для оплаты услуг"
descriptions:
  title_mappings:
    "внутрибанковский перевод": "Перевод внутри банка"
    "yandex.lavka": "Яндекс.Лавка"
    "samokat": "Самокат"
  operation_signatures:
    "перевод": "Перевод"
    "пополнение": "Пополнение"
    "списание": "Списание"
    "внутрибанковский перевод": "Перевод внутри банка"
    "оплата": "Оплата"
output:
  csv_path: "./transactions1.csv"
